name : merge

on:
  schedule:
    - cron: '*/1 * * * *' # Executa a cada 1 minuto
  workflow_dispatch: # Permite acionar manualmente

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set conta
      run: |
        git config --local user.email "ramon.piologo@hotmail.com"
        git config --local user.name "Pioloko"
        
    - name: merge com linux 
      run: |
        git fetch origin # Busca as atualizações do repositório remoto
        git checkout merge
        git merge origin/card-02 --no-ff # Mescla a branch card-02
        git merge origin/card-01 --no-ff # Mescla a branch card-01
        git push origin merge
