name : merge

on:
  schedule:
  #   - cron: '*/1 * * * *' # Executa a cada 1 minuto
  # workflow_dispatch: # Permite acionar manualmente

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set conta
      run: |
        git config --local user.email "ramon.piologo@hotmail.com"
        git config --local user.name "Pioloko"
        
    - name: List branches with 'card-' pattern
      id: list-branches
      run: |
        git fetch origin # Busca as atualizações do repositório remoto
        branches=$(git branch -a --format='%(refname:short)' | grep -E 'card-[0-9]+$' | xargs)
        echo "::set-output name=branches::$branches"

    - name: Merge card branches
      run: |
        git checkout merge2

        for branch in ${{ steps.list-branches.outputs.branches }}; do
          git merge --no-ff "$branch" --no-edit
        done

        git push origin merge2
