name: merge

on:
  schedule:
    - cron: '*/10 * * * *' # Executa a cada 1 minuto
  workflow_dispatch: # Permite acionar manualmente

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set conta
        run: |
          git config --local user.email "ramon.piologo@hotmail.com"
          git config --local user.name "Pioloko"
        
      - name: merge com linux 
        run: |
          git fetch origin # Busca as atualizações do repositório remoto
          git checkout merge

          # Loop para mesclar todas as branches 'card-*'
          for branch in $(git branch --format='%(refname:short)' | grep -E 'origin/card-[0-9]+$'); do
            git merge "$branch" --no-ff # Mescla cada branch 'card-*'
          done

          git push origin merge # Faz push da branch 'merge' com as mesclagens
