name: merge

on:
  schedule:
    - cron: '*/1 * * * *'  # Executa a cada 1 minuto
  workflow_dispatch:       # Permite acionar manualmente

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setar informações de usuário
        run: |
          git config --local user.email "ramon.piologo@hotmail.com"
          git config --local user.name "Pioloko"

      - name: Busca as pastas e da checkout
        run: |
          git fetch origin  # Busca as atualizações do repositório remoto
          git checkout merge
          
      - name: Faz o merge
        run: |
          # Loop para mesclar todas as branches 'card-*'
          for branch in $(git branch --format='%(refname:short)' | grep -E 'origin/card-[0-9]+$'); do
            git merge "$branch" --no-ff  # Mescla cada branch 'card-*'
            git push origin merge  # Faz push da branch 'merge' com as mesclagens
          done
