name : merge

on:
  schedule:
    - cron: '*/1 * * * *' # Executa a cada 1 minuto
  workflow_dispatch: # Permite acionar manualmente

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: merge com linux 
      run: |
        for branch in $(git branch --format='%(refname:short)' | grep -E 'card-[0-9]+$'); do
          git checkout merge
          git merge "$branch" --no-edit --no-ff
        done
        git push origin merge
